#======================================================================
# Makefile for %[Package name: %]
# 
# Copyright (C) %y %U %a
# National Snow and Ice Data Center, University of Colorado, Boulder
#----------------------------------------------------------------------

#------------------------------------------------------------------------
# configuration section
#
# for compiling, installing and distributing you should be able
# to change these variables here and nowhere else and it should work
#
#
TOPDIR = $(NRTSITOP)

LIBDIR = $(TOPDIR)/lib
INCDIR = $(TOPDIR)/include
BINDIR = $(TOPDIR)/bin
SRCDIR = $(TOPDIR)/src


