;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        kill-region
        wgrep-finish-edit
        ))

(setq mc/cmds-to-run-once
      '(
        multiple-cursors-hydra/mc/mark-next-like-this
        ))
