;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	end-of-visual-line
	kill-region
	message-beginning-of-line
	wgrep-finish-edit
	yaml-electric-backspace
	))

(setq mc/cmds-to-run-once
      '(
	multiple-cursors-hydra/mc/mark-next-like-this
	multiple-cursors-hydra/mc/skip-to-next-like-this
	))
