;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	clipboard-kill-ring-save
	dabbrev-expand
	ein:worksheet-split-cell-at-point
	electric-newline-and-maybe-indent
	end-of-visual-line
	forward-sexp
	indent-for-tab-command
	ivy-wgrep-change-to-wgrep-mode
	kill-region
	markdown-exdent-or-delete
	message-beginning-of-line
	nxml-electric-slash
	org-beginning-of-line
	org-delete-char
	org-end-of-line
	org-kill-line
	org-self-insert-command
	org-shiftdown
	org-shiftup
	org-yank
	save-some-buffers
	sgml-slash
	wgrep-finish-edit
	yaml-electric-backspace
	yaml-electric-bar-and-angle
	yaml-electric-dash-and-dot
	))

(setq mc/cmds-to-run-once
      '(
	backward-kill-sentence
	counsel-M-x
	dired-toggle-read-only
	multiple-cursors-hydra/body
	multiple-cursors-hydra/mc/edit-lines-and-exit
	multiple-cursors-hydra/mc/mark-all-like-this-and-exit
	multiple-cursors-hydra/mc/mark-next-like-this
	multiple-cursors-hydra/mc/skip-to-next-like-this
	multiple-cursors-hydra/mc/unmark-next-like-this
	next-error-no-select
	swiper
	))
