(deftheme nord
  "Created 2017-10-26.")

(custom-theme-set-faces
 'nord
 '(bold ((((class color) (min-colors 89)) (:weight bold))))
 '(bold-italic ((((class color) (min-colors 89)) (:weight bold :slant italic))))
 '(error ((((class color) (min-colors 89)) (:foreground "#BF616A" :weight bold))))
 '(escape-glyph ((((class color) (min-colors 89)) (:foreground "#D08770"))))
 '(font-lock-builtin-face ((((class color) (min-colors 89)) (:foreground "#81A1C1"))))
 '(font-lock-comment-face ((((class color) (min-colors 89)) (:foreground "#75829c"))))
 '(font-lock-comment-delimiter-face ((((class color) (min-colors 89)) (:foreground "#75829c"))))
 '(font-lock-constant-face ((((class color) (min-colors 89)) (:foreground "#81A1C1"))))
 '(font-lock-doc-face ((((class color) (min-colors 89)) (:foreground "#75829c"))))
 '(font-lock-function-name-face ((((class color) (min-colors 89)) (:foreground "#88C0D0"))))
 '(font-lock-keyword-face ((((class color) (min-colors 89)) (:foreground "#81A1C1"))))
 '(font-lock-negation-char-face ((((class color) (min-colors 89)) (:foreground "#81A1C1"))))
 '(font-lock-preprocessor-face ((((class color) (min-colors 89)) (:foreground "#5E81AC" :weight bold))))
 '(font-lock-regexp-grouping-backslash ((((class color) (min-colors 89)) (:foreground "#EBCB8B"))))
 '(font-lock-regexp-grouping-construct ((((class color) (min-colors 89)) (:foreground "#EBCB8B"))))
 '(font-lock-string-face ((((class color) (min-colors 89)) (:foreground "#A3BE8C"))))
 '(font-lock-type-face ((((class color) (min-colors 89)) (:foreground "#8FBCBB"))))
 '(font-lock-variable-name-face ((((class color) (min-colors 89)) (:foreground "#D8DEE9"))))
 '(font-lock-warning-face ((((class color) (min-colors 89)) (:foreground "#EBCB8B"))))
 '(italic ((((class color) (min-colors 89)) (:slant italic))))
 '(shadow ((((class color) (min-colors 89)) (:foreground "#4C566A"))))
 '(underline ((((class color) (min-colors 89)) (:underline t))))
 '(warning ((((class color) (min-colors 89)) (:foreground "#EBCB8B" :weight bold))))
 '(c-annotation-face ((((class color) (min-colors 89)) (:foreground "#D08770"))))
 '(diff-added ((((class color) (min-colors 89)) (:foreground "#A3BE8C"))))
 '(diff-changed ((((class color) (min-colors 89)) (:foreground "#EBCB8B"))))
 '(diff-context ((((class color) (min-colors 89)) (:inherit default))))
 '(diff-file-header ((((class color) (min-colors 89)) (:foreground "#88C0D0"))))
 '(diff-function ((((class color) (min-colors 89)) (:foreground "#8FBCBB"))))
 '(diff-header ((((class color) (min-colors 89)) (:foreground "#81A1C1" :weight bold))))
 '(diff-hunk-header ((((class color) (min-colors 89)) (:foreground "#81A1C1" :background "#2E3440"))))
 '(diff-indicator-added ((((class color) (min-colors 89)) (:foreground "#A3BE8C"))))
 '(diff-indicator-changed ((((class color) (min-colors 89)) (:foreground "#EBCB8B"))))
 '(diff-indicator-removed ((((class color) (min-colors 89)) (:foreground "#BF616A"))))
 '(diff-nonexistent ((((class color) (min-colors 89)) (:foreground "#BF616A"))))
 '(diff-refine-added ((((class color) (min-colors 89)) (:foreground "#A3BE8C"))))
 '(diff-refine-changed ((((class color) (min-colors 89)) (:foreground "#EBCB8B"))))
 '(diff-refine-removed ((((class color) (min-colors 89)) (:foreground "#BF616A"))))
 '(diff-removed ((((class color) (min-colors 89)) (:foreground "#BF616A"))))
 '(border ((((class color) (min-colors 89)) (:foreground "#D8DEE9"))))
 '(buffer-menu-buffer ((((class color) (min-colors 89)) (:foreground "#D8DEE9" :weight bold))))
 '(button ((((class color) (min-colors 89)) (:background "#2E3440" :foreground "#88C0D0" :box (:line-width 2 :color "#D8DEE9" :style sunken-button)))))
 '(completions-annotations ((((class color) (min-colors 89)) (:foreground "#81A1C1"))))
 '(completions-common-part ((((class color) (min-colors 89)) (:foreground "#88C0D0" :weight bold))))
 '(completions-first-difference ((((class color) (min-colors 89)) (:foreground "#BF616A"))))
 '(custom-button ((((class color) (min-colors 89)) (:background "#2E3440" :foreground "#88C0D0" :box (:line-width 2 :color "#D8DEE9" :style sunken-button)))))
 '(custom-button-mouse ((((class color) (min-colors 89)) (:background "#D8DEE9" :foreground "#2E3440" :box (:line-width 2 :color "#D8DEE9" :style sunken-button)))))
 '(custom-button-pressed ((((class color) (min-colors 89)) (:background "#ECEFF4" :foreground "#2E3440" :box (:line-width 2 :color "#D8DEE9" :style sunken-button)))))
 '(custom-button-pressed-unraised ((((class color) (min-colors 89)) (:background "#D8DEE9" :foreground "#2E3440" :box (:line-width 2 :color "#D8DEE9" :style sunken-button)))))
 '(custom-button-unraised ((((class color) (min-colors 89)) (:background "#2E3440" :foreground "#88C0D0" :box (:line-width 2 :color "#D8DEE9" :style sunken-button)))))
 '(custom-changed ((((class color) (min-colors 89)) (:foreground "#EBCB8B"))))
 '(custom-comment ((((class color) (min-colors 89)) (:foreground "#75829c"))))
 '(custom-comment-tag ((((class color) (min-colors 89)) (:foreground "#8FBCBB"))))
 '(custom-documentation ((((class color) (min-colors 89)) (:foreground "#D8DEE9"))))
 '(custom-group-tag ((((class color) (min-colors 89)) (:foreground "#88C0D0" :weight bold))))
 '(custom-group-tag-1 ((((class color) (min-colors 89)) (:foreground "#88C0D0" :weight bold))))
 '(custom-invalid ((((class color) (min-colors 89)) (:foreground "#BF616A"))))
 '(custom-modified ((((class color) (min-colors 89)) (:foreground "#EBCB8B"))))
 '(custom-rogue ((((class color) (min-colors 89)) (:foreground "#D08770" :background "#434C5E"))))
 '(custom-saved ((((class color) (min-colors 89)) (:foreground "#A3BE8C"))))
 '(custom-set ((((class color) (min-colors 89)) (:foreground "#88C0D0"))))
 '(custom-state ((((class color) (min-colors 89)) (:foreground "#A3BE8C"))))
 '(custom-themed ((((class color) (min-colors 89)) (:foreground "#88C0D0" :background "#434C5E"))))
 '(cursor ((((class color) (min-colors 89)) (:background "#D8DEE9"))))
 '(fringe ((((class color) (min-colors 89)) (:foreground "#D8DEE9" :background "#2E3440"))))
 '(file-name-shadow ((((class color) (min-colors 89)) (:inherit shadow))))
 '(header-line ((((class color) (min-colors 89)) (:foreground "#D8DEE9" :background "#434C5E"))))
 '(help-argument-name ((((class color) (min-colors 89)) (:foreground "#88C0D0"))))
 '(highlight ((((class color) (min-colors 89)) (:foreground "#88C0D0" :background "#434C5E"))))
 '(hl-line ((((class color) (min-colors 89)) (:background "#3B4252"))))
 '(info-menu-star ((((class color) (min-colors 89)) (:foreground "#81A1C1"))))
 '(isearch ((((class color) (min-colors 89)) (:foreground "#2E3440" :background "#88C0D0"))))
 '(isearch-fail ((((class color) (min-colors 89)) (:foreground "#BF616A"))))
 '(link ((((class color) (min-colors 89)) (:underline t))))
 '(link-visited ((((class color) (min-colors 89)) (:underline t))))
 '(linum ((((class color) (min-colors 89)) (:foreground "#4C566A" :background "#2E3440"))))
 '(match ((((class color) (min-colors 89)) (:inherit isearch))))
 '(message-cited-text ((((class color) (min-colors 89)) (:foreground "#D8DEE9"))))
 '(message-header-cc ((((class color) (min-colors 89)) (:foreground "#81A1C1"))))
 '(message-header-name ((((class color) (min-colors 89)) (:foreground "#8FBCBB"))))
 '(message-header-other ((((class color) (min-colors 89)) (:foreground "#D8DEE9"))))
 '(message-header-subject ((((class color) (min-colors 89)) (:foreground "#88C0D0"))))
 '(message-header-to ((((class color) (min-colors 89)) (:foreground "#81A1C1"))))
 '(message-header-xheader ((((class color) (min-colors 89)) (:foreground "#EBCB8B"))))
 '(message-mml ((((class color) (min-colors 89)) (:foreground "#5E81AC"))))
 '(message-separator ((((class color) (min-colors 89)) (:inherit shadow))))
 '(minibuffer-prompt ((((class color) (min-colors 89)) (:foreground "#88C0D0" :weight bold))))
 '(mm-command-output ((((class color) (min-colors 89)) (:foreground "#88C0D0"))))
 '(mode-line ((((class color) (min-colors 89)) (:foreground "#88C0D0" :background "#4C566A"))))
 '(mode-line-buffer-id ((((class color) (min-colors 89)) (:weight bold))))
 '(mode-line-highlight ((((class color) (min-colors 89)) (:inherit highlight))))
 '(mode-line-inactive ((((class color) (min-colors 89)) (:foreground "#D8DEE9" :background "#3B4252"))))
 '(next-error ((((class color) (min-colors 89)) (:inherit error))))
 '(nobreak-space ((((class color) (min-colors 89)) (:foreground "#4C566A"))))
 '(outline-1 ((((class color) (min-colors 89)) (:foreground "#88C0D0" :weight bold))))
 '(outline-2 ((((class color) (min-colors 89)) (:inherit outline-1))))
 '(outline-3 ((((class color) (min-colors 89)) (:inherit outline-1))))
 '(outline-4 ((((class color) (min-colors 89)) (:inherit outline-1))))
 '(outline-5 ((((class color) (min-colors 89)) (:inherit outline-1))))
 '(outline-6 ((((class color) (min-colors 89)) (:inherit outline-1))))
 '(outline-7 ((((class color) (min-colors 89)) (:inherit outline-1))))
 '(outline-8 ((((class color) (min-colors 89)) (:inherit outline-1))))
 '(package-description ((((class color) (min-colors 89)) (:foreground "#D8DEE9"))))
 '(package-help-section-name ((((class color) (min-colors 89)) (:foreground "#88C0D0" :weight bold))))
 '(package-name ((((class color) (min-colors 89)) (:foreground "#88C0D0"))))
 '(package-status-available ((((class color) (min-colors 89)) (:foreground "#8FBCBB"))))
 '(package-status-avail-obso ((((class color) (min-colors 89)) (:foreground "#8FBCBB" :slant italic))))
 '(package-status-built-in ((((class color) (min-colors 89)) (:foreground "#81A1C1"))))
 '(package-status-dependency ((((class color) (min-colors 89)) (:foreground "#88C0D0" :slant italic))))
 '(package-status-disabled ((((class color) (min-colors 89)) (:foreground "#4C566A"))))
 '(package-status-external ((((class color) (min-colors 89)) (:foreground "#D08770" :slant italic))))
 '(package-status-held ((((class color) (min-colors 89)) (:foreground "#D8DEE9" :weight bold))))
 '(package-status-new ((((class color) (min-colors 89)) (:foreground "#A3BE8C"))))
 '(package-status-incompat ((((class color) (min-colors 89)) (:foreground "#BF616A"))))
 '(package-status-installed ((((class color) (min-colors 89)) (:foreground "#8FBCBB" :weight bold))))
 '(package-status-unsigned ((((class color) (min-colors 89)) (:underline "#EBCB8B"))))
 '(query-replace ((((class color) (min-colors 89)) (:foreground "#88C0D0" :background "#434C5E"))))
 '(region ((((class color) (min-colors 89)) (:foreground "#2E3440" :background "#88C0D0"))))
 '(scroll-bar ((((class color) (min-colors 89)) (:background "#4C566A"))))
 '(secondary-selection ((((class color) (min-colors 89)) (:background "#434C5E"))))
 '(show-paren-match ((((class color) (min-colors 89)) (:foreground "#2E3440" :background "#88C0D0"))))
 '(show-paren-mismatch ((((class color) (min-colors 89)) (:background "#BF616A"))))
 '(success ((((class color) (min-colors 89)) (:foreground "#A3BE8C"))))
 '(tool-bar ((((class color) (min-colors 89)) (:foreground "#D8DEE9" :background "#4C566A"))))
 '(tooltip ((((class color) (min-colors 89)) (:foreground "#2E3440" :background "#D8DEE9"))))
 '(trailing-whitespace ((((class color) (min-colors 89)) (:foreground "#4C566A"))))
 '(tty-menu-disabled-face ((((class color) (min-colors 89)) (:foreground "#3B4252"))))
 '(tty-menu-enabled-face ((((class color) (min-colors 89)) (:background "#434C5E" foreground "#D8DEE9"))))
 '(tty-menu-selected-face ((((class color) (min-colors 89)) (:foreground "#88C0D0" :underline t))))
 '(vc-conflict-state ((((class color) (min-colors 89)) (:foreground "#D08770"))))
 '(vc-edited-state ((((class color) (min-colors 89)) (:foreground "#EBCB8B"))))
 '(vc-locally-added-state ((((class color) (min-colors 89)) (:underline "#A3BE8C"))))
 '(vc-locked-state ((((class color) (min-colors 89)) (:foreground "#5E81AC"))))
 '(vc-missing-state ((((class color) (min-colors 89)) (:foreground "#BF616A"))))
 '(vc-needs-update-state ((((class color) (min-colors 89)) (:foreground "#D08770"))))
 '(vc-removed-state ((((class color) (min-colors 89)) (:foreground "#BF616A"))))
 '(vc-state-base ((((class color) (min-colors 89)) (:foreground "#D8DEE9"))))
 '(vc-up-to-date-state ((((class color) (min-colors 89)) (:foreground "#88C0D0"))))
 '(vertical-border ((((class color) (min-colors 89)) (:foreground "#434C5E"))))
 '(widget-button-pressed ((((class color) (min-colors 89)) (:foreground "#81A1C1" :background "#3B4252"))))
 '(widget-documentation ((((class color) (min-colors 89)) (:foreground "#D8DEE9"))))
 '(widget-field ((((class color) (min-colors 89)) (:background "#434C5E" :foreground "#D8DEE9"))))
 '(widget-single-line-field ((((class color) (min-colors 89)) (:background "#434C5E" :foreground "#D8DEE9"))))
 '(window-divider ((((class color) (min-colors 89)) (:background "#4C566A"))))
 '(window-divider-first-pixel ((((class color) (min-colors 89)) (:background "#4C566A"))))
 '(window-divider-last-pixel ((((class color) (min-colors 89)) (:background "#4C566A"))))
 '(js2-function-call ((((class color) (min-colors 89)) (:foreground "#88C0D0"))))
 '(js2-private-function-call ((((class color) (min-colors 89)) (:foreground "#88C0D0"))))
 '(js2-jsdoc-html-tag-delimiter ((((class color) (min-colors 89)) (:foreground "#ECEFF4"))))
 '(js2-jsdoc-html-tag-name ((((class color) (min-colors 89)) (:foreground "#81A1C1"))))
 '(js2-external-variable ((((class color) (min-colors 89)) (:foreground "#D8DEE9"))))
 '(js2-function-param ((((class color) (min-colors 89)) (:foreground "#D8DEE9"))))
 '(js2-jsdoc-value ((((class color) (min-colors 89)) (:foreground "#75829c"))))
 '(js2-jsdoc-tag ((((class color) (min-colors 89)) (:foreground "#8FBCBB"))))
 '(js2-jsdoc-type ((((class color) (min-colors 89)) (:foreground "#8FBCBB"))))
 '(js2-private-member ((((class color) (min-colors 89)) (:foreground "#D8DEE9"))))
 '(js2-object-property ((((class color) (min-colors 89)) (:foreground "#D8DEE9"))))
 '(js2-error ((((class color) (min-colors 89)) (:foreground "#BF616A"))))
 '(js2-warning ((((class color) (min-colors 89)) (:foreground "#EBCB8B"))))
 '(js2-instance-member ((((class color) (min-colors 89)) (:foreground "#D8DEE9"))))
 '(markdown-blockquote-face ((((class color) (min-colors 89)) (:foreground "#75829c"))))
 '(markdown-bold-face ((((class color) (min-colors 89)) (:inherit bold))))
 '(markdown-header-face-1 ((((class color) (min-colors 89)) (:foreground "#88C0D0"))))
 '(markdown-header-face-2 ((((class color) (min-colors 89)) (:foreground "#88C0D0"))))
 '(markdown-header-face-3 ((((class color) (min-colors 89)) (:foreground "#88C0D0"))))
 '(markdown-header-face-4 ((((class color) (min-colors 89)) (:foreground "#88C0D0"))))
 '(markdown-header-face-5 ((((class color) (min-colors 89)) (:foreground "#88C0D0"))))
 '(markdown-header-face-6 ((((class color) (min-colors 89)) (:foreground "#88C0D0"))))
 '(markdown-inline-code-face ((((class color) (min-colors 89)) (:foreground "#8FBCBB"))))
 '(markdown-italic-face ((((class color) (min-colors 89)) (:inherit italic))))
 '(markdown-link-face ((((class color) (min-colors 89)) (:foreground "#88C0D0"))))
 '(markdown-markup-face ((((class color) (min-colors 89)) (:foreground "#81A1C1"))))
 '(markdown-reference-face ((((class color) (min-colors 89)) (:inherit markdown-link-face))))
 '(markdown-url-face ((((class color) (min-colors 89)) (:foreground "#D8DEE9" :underline t))))
 '(company-echo-common ((((class color) (min-colors 89)) (:foreground "#2E3440" :background "#D8DEE9"))))
 '(company-preview ((((class color) (min-colors 89)) (:foreground "#D8DEE9" :background "#5E81AC"))))
 '(company-preview-common ((((class color) (min-colors 89)) (:foreground "#2E3440" :background "#88C0D0"))))
 '(company-preview-search ((((class color) (min-colors 89)) (:foreground "#2E3440" :background "#88C0D0"))))
 '(company-scrollbar-bg ((((class color) (min-colors 89)) (:foreground "#3B4252" :background "#3B4252"))))
 '(company-scrollbar-fg ((((class color) (min-colors 89)) (:foreground "#434C5E" :background "#434C5E"))))
 '(company-template-field ((((class color) (min-colors 89)) (:foreground "#2E3440" :background "#8FBCBB"))))
 '(company-tooltip ((((class color) (min-colors 89)) (:foreground "#D8DEE9" :background "#434C5E"))))
 '(company-tooltip-annotation ((((class color) (min-colors 89)) (:foreground "#D08770"))))
 '(company-tooltip-annotation-selection ((((class color) (min-colors 89)) (:foreground "#D08770" :weight bold))))
 '(company-tooltip-common ((((class color) (min-colors 89)) (:foreground "#88C0D0"))))
 '(company-tooltip-common-selection ((((class color) (min-colors 89)) (:foreground "#88C0D0" :background "#4C566A"))))
 '(company-tooltip-mouse ((((class color) (min-colors 89)) (:inherit highlight))))
 '(company-tooltip-selection ((((class color) (min-colors 89)) (:background "#4C566A" :weight bold))))
 '(flycheck-error ((((class color) (min-colors 89)) (:underline (:style wave :color "#BF616A")))))
 '(flycheck-fringe-error ((((class color) (min-colors 89)) (:foreground "#BF616A" :weight bold))))
 '(flycheck-fringe-info ((((class color) (min-colors 89)) (:foreground "#88C0D0" :weight bold))))
 '(flycheck-fringe-warning ((((class color) (min-colors 89)) (:foreground "#EBCB8B" :weight bold))))
 '(flycheck-info ((((class color) (min-colors 89)) (:underline (:style wave :color "#88C0D0")))))
 '(flycheck-warning ((((class color) (min-colors 89)) (:underline (:style wave :color "#EBCB8B")))))
 '(magit-diff-context-highlight ((((class color) (min-colors 89)) (:background "#434C5E"))))
 '(magit-diffstat-added ((((class color) (min-colors 89)) (:foreground "#A3BE8C"))))
 '(magit-diffstat-removed ((((class color) (min-colors 89)) (:foreground "#BF616A"))))
 '(magit-hash ((((class color) (min-colors 89)) (:foreground "#88C0D0"))))
 '(magit-log-author ((((class color) (min-colors 89)) (:foreground "#8FBCBB"))))
 '(magit-process-ng ((((class color) (min-colors 89)) (:foreground "#EBCB8B" :weight bold))))
 '(magit-process-ok ((((class color) (min-colors 89)) (:foreground "#A3BE8C" :weight bold))))
 '(magit-section-heading ((((class color) (min-colors 89)) (:foreground "#8FBCBB" :weight bold))))
 '(magit-section-highlight ((((class color) (min-colors 89)) (:background "#434C5E"))))
 '(org-level-1 ((((class color) (min-colors 89)) (:foreground "#88C0D0" :weight bold))))
 '(org-level-2 ((((class color) (min-colors 89)) (:inherit org-level-1 :foreground "#5FAABF"))))
 '(org-level-3 ((((class color) (min-colors 89)) (:inherit org-level-1 :foreground "#9ca4d0"))))
 '(org-level-4 ((((class color) (min-colors 89)) (:inherit org-level-1 :foreground "#a29cd0"))))
 '(org-level-5 ((((class color) (min-colors 89)) (:inherit org-level-1))))
 '(org-level-6 ((((class color) (min-colors 89)) (:inherit org-level-2))))
 '(org-level-7 ((((class color) (min-colors 89)) (:inherit org-level-3))))
 '(org-level-8 ((((class color) (min-colors 89)) (:inherit org-level-4))))
 '(org-agenda-structure ((((class color) (min-colors 89)) (:foreground "#81A1C1"))))
 '(org-agenda-date ((((class color) (min-colors 89)) (:foreground "#88C0D0" :underline nil))))
 '(org-agenda-done ((((class color) (min-colors 89)) (:foreground "#A3BE8C"))))
 '(org-agenda-dimmed-todo-face ((((class color) (min-colors 89)) (:background "#EBCB8B"))))
 '(org-block ((((class color) (min-colors 89)) (:foreground "#D8DEE9"))))
 '(org-block-begin-line ((((class color) (min-colors 89)) (:foreground "#8FBCBB"))))
 '(org-block-end-line ((((class color) (min-colors 89)) (:foreground "#8FBCBB"))))
 '(org-checkbox ((((class color) (min-colors 89)) (:foreground "#81A1C1"))))
 '(org-checkbox-statistics-done ((((class color) (min-colors 89)) (:foreground "#A3BE8C"))))
 '(org-checkbox-statistics-todo ((((class color) (min-colors 89)) (:foreground "#EBCB8B"))))
 '(org-code ((((class color) (min-colors 89)) (:foreground "#8FBCBB"))))
 '(org-column ((((class color) (min-colors 89)) (:background "#434C5E"))))
 '(org-column-title ((((class color) (min-colors 89)) (:inherit org-column :weight bold :underline t))))
 '(org-date ((((class color) (min-colors 89)) (:foreground "#88C0D0"))))
 '(org-document-info ((((class color) (min-colors 89)) (:foreground "#D8DEE9"))))
 '(org-document-info-keyword ((((class color) (min-colors 89)) (:foreground "#4C566A" :weight bold))))
 '(org-document-title ((((class color) (min-colors 89)) (:foreground "#88C0D0" :weight bold))))
 '(org-done ((((class color) (min-colors 89)) (:foreground "#A3BE8C" :weight bold))))
 '(org-ellipsis ((((class color) (min-colors 89)) (:foreground "#4C566A"))))
 '(org-footnote ((((class color) (min-colors 89)) (:foreground "#88C0D0"))))
 '(org-formula ((((class color) (min-colors 89)) (:foreground "#81A1C1"))))
 '(org-hide ((((class color) (min-colors 89)) (:foreground "#2E3440" :background "#2E3440"))))
 '(org-link ((((class color) (min-colors 89)) (:underline t))))
 '(org-scheduled ((((class color) (min-colors 89)) (:foreground "#A3BE8C"))))
 '(org-scheduled-previously ((((class color) (min-colors 89)) (:foreground "#EBCB8B"))))
 '(org-scheduled-today ((((class color) (min-colors 89)) (:foreground "#88C0D0"))))
 '(org-special-keyword ((((class color) (min-colors 89)) (:foreground "#81A1C1"))))
 '(org-table ((((class color) (min-colors 89)) (:foreground "#81A1C1"))))
 '(org-todo ((((class color) (min-colors 89)) (:foreground "#EBCB8B" :weight bold))))
 '(org-upcoming-deadline ((((class color) (min-colors 89)) (:foreground "#D08770"))))
 '(org-warning ((((class color) (min-colors 89)) (:foreground "#EBCB8B" :weight bold))))
 '(ido-only-match ((((class color) (min-colors 89)) (:foreground "#88C0D0"))))
 '(org-sexp-date ((((class color) (min-colors 89)) (:foreground "#8FBCBB"))))
 '(ido-first-match ((((class color) (min-colors 89)) (:foreground "#88C0D0" :weight bold))))
 '(ido-subdir ((((class color) (min-colors 89)) (:foreground "#81A1C1"))))
 '(org-quote ((((class color) (min-colors 89)) (:inherit org-block :slant italic))))
 '(org-verse ((((class color) (min-colors 89)) (:inherit org-block :slant italic))))
 '(org-agenda-date-weekend ((((class color) (min-colors 89)) (:foreground "#81A1C1"))))
 '(org-agenda-date-today ((((class color) (min-colors 89)) (:foreground "#88C0D0" :weight bold))))
 '(org-agenda-done ((((class color) (min-colors 89)) (:foreground "#A3BE8C"))))
 '(org-verbatim ((((class color) (min-colors 89)) (:foreground "#8FBCBB"))))
 '(default ((((class color) (min-colors 89)) (:foreground "#D8DEE9" :background "#2E3440")))))

(provide-theme 'nord)
