(deftheme nord
  "Created 2018-02-23.")

(custom-theme-set-faces
 'nord
 '(cursor ((t (:foreground "gray13" :background "#D8DEE9"))))
 '(fixed-pitch ((t (:family "Monospace"))))
 '(variable-pitch ((((type w32)) (:foundry "outline" :family "Arial")) (t (:family "Sans Serif"))))
 '(escape-glyph ((t (:foreground "#D08770"))))
 '(minibuffer-prompt ((t (:weight bold :foreground "#88C0D0"))))
 '(highlight ((t (:foreground "#88C0D0" :background "#434C5E"))))
 '(region ((t (:background "#434C5E"))))
 '(shadow ((t (:foreground "#4C566A"))))
 '(secondary-selection ((t (:background "#434C5E"))))
 '(trailing-whitespace ((t (:weight bold :foreground "#4C566A" :background "white"))))
 '(font-lock-builtin-face ((t (:foreground "#81A1C1"))))
 '(font-lock-comment-delimiter-face ((t (:foreground "#4c566a"))))
 '(font-lock-comment-face ((t (:foreground "#4c566a"))))
 '(font-lock-constant-face ((t (:foreground "#81A1C1"))))
 '(font-lock-doc-face ((t (:foreground "#4c566a"))))
 '(font-lock-function-name-face ((t (:foreground "#88C0D0"))))
 '(font-lock-keyword-face ((t (:foreground "#81A1C1"))))
 '(font-lock-negation-char-face ((t (:foreground "#81A1C1"))))
 '(font-lock-preprocessor-face ((t (:weight bold :foreground "#5E81AC"))))
 '(font-lock-regexp-grouping-backslash ((t (:foreground "#EBCB8B"))))
 '(font-lock-regexp-grouping-construct ((t (:foreground "#EBCB8B"))))
 '(font-lock-string-face ((t (:foreground "#A3BE8C"))))
 '(font-lock-type-face ((t (:foreground "#8FBCBB"))))
 '(font-lock-variable-name-face ((t (:foreground "#B48EAD"))))
 '(font-lock-warning-face ((t (:weight bold :foreground "#EBCB8B"))))
 '(button ((t (:underline (:color foreground-color :style line) :box (:line-width 2 :color "#D8DEE9" :style sunken-button) :foreground "#88C0D0" :background "#2E3440"))))
 '(link ((t (:underline (:color foreground-color :style line) :foreground "#68a5e9"))))
 '(link-visited ((t (:underline (:color foreground-color :style line)))))
 '(fringe ((t (:foreground "#D8DEE9" :background "#2E3440"))))
 '(header-line ((t (:foreground "#D8DEE9" :background "#434C5E"))))
 '(tooltip ((t (:foreground "#2E3440" :background "#D8DEE9"))))
 '(mode-line ((t (:foreground "#88C0D0" :background "#4C566A"))))
 '(mode-line-buffer-id ((t (:weight bold))))
 '(mode-line-emphasis ((t (:weight bold))))
 '(mode-line-highlight ((t (:inherit (highlight)))))
 '(mode-line-inactive ((t (:foreground "#D8DEE9" :background "#3B4252"))))
 '(isearch ((t (:foreground "#2E3440" :background "#88C0D0"))))
 '(isearch-fail ((t (:foreground "#BF616A"))))
 '(lazy-highlight ((t (:underline (:color foreground-color :style line) :foreground "#ab75c3" :background "gray13"))))
 '(match ((t (:inherit (isearch)))))
 '(next-error ((t (:inherit (error)))))
 '(query-replace ((t (:foreground "#88C0D0" :background "#434C5E"))))
 '(org-level-1 ((t (:weight bold :foreground "#88C0D0"))))
 '(org-level-2 ((t (:inherit (org-level-1)))))
 '(org-level-3 ((t (:inherit (org-level-1)))))
 '(org-level-4 ((t (:inherit (org-level-1)))))
 '(default ((t (:family "Inconsolata" :foundry "nil" :width normal :height 200 :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "#D8DEE9" :background "#2E3440" :stipple nil :inherit nil)))))

(provide-theme 'nord)
